# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f36e347cae58c3fddafac16f68bd725af62791c02e4fe03c8d6e1d6b9f037aa8b01bee3fe33eed54c7746655e2a924a47e5ccefad3b292ec8ff315ca692e04ef

test:
  secret_key_base: 8c24f84a8002f48b662afce532fd4e399003dba3f9f0aa3c407edc4f6c90806f363b2c025edfd24a314737e459c8f90ab9dffe578a7a2d21a6cf3de2f1bb2329

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
